apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: my-ns
spec:
  template:
    spec:
      containers:
        - name: nginx-app
          resources:
            requests:
              memory: "264Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
